#!/usr/bin/env bash
#   at 9
c=1
while ((c < 21))
do
	echo $i
	case "$i" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		esac
	((c++))
done
