#!/usr/bin/env bash

# This script counts time and prints every minute

hours=0
minutes=1

while [ $hours -ne 13 ]
do
    echo "Hour: $hours"

    while [ $minutes -ne 60 ]
    do
        if [ $minutes -lt 10 ]; then
            echo "0$minutes"
        else
            echo "$minutes"
        fi
        ((minutes++))
    done

    minutes=1
    ((hours++))
done
